### ISSUE TITLE
TransT tracker integration

### ISSUE THREAD

**Issue by dschoerk** [cvat-ai/cvat-opencv#14]
as originally posted in https://github.com/openvinotoolkit/cvat/issues/4768 

Hi, I've recently started to use CVAT to annotate videos of traffic scenes. Before coming across CVAT I briefly experimented with Supervisely and was very impressed by their [semi-automatic video annotation with TransT ](https://www.youtube.com/watch?v=EMvqTFu1ILE). TransT is a single object tracking algorithm and was presented recently at CVPR21, a Pytorch implementation is available [here](https://github.com/chenxin-dlut/TransT). So I picked that up and integrated it into CVAT as a new tracking tool. If you find this useful I would like to open a pull request for this new feature.

a demo video showing the workflow and a comparison between TransT and SiamMask if you are interested:
https://www.youtube.com/watch?v=_oT44BXMaJY

**Comment by bsekachev** [comment]
Hi, @dschoerk 

That would be great if you can contribuite it. BTW, how many FPS does it work on your CPU/GPU?
We are ready to assist and help you with this integration.

**Comment by malfonso0** [comment]
hi.. would love to have it in my local implementation.. can you share the code to generate the tracker ?

**Comment by bsekachev** [comment]
@malfonso0 You can find this code in the PR above, isn't it?

**Comment by dschoerk** [comment]
> yess.. sorry i reply it fast and then i remember that you mention the PR. the frame -1 -> frame its necessary ? on the tracker call ? will this affect also the siammask?

hi, this will affect all trackers, but conceptionally this should be correct for all tracking algorithms that require initialization with template ROI and track that to successive frames. I tested it with both SiamMask and the provided TransT tracker. it's an improvement for both algorithms.

**Comment by malfonso0** [comment]
ok thanks. i will applyit.
Can i ask you.. how were you able to "create" the tracker.. ? did you follow the siammask code to create yours?, i couldnt find any doc on that.
i was planning on creating one using SORT or DEEPSORT as it is very helpfully for anotating videos

**Comment by dschoerk** [comment]
I basically containerized the TransT implementation linked in the first post and took the SiamMask integration in CVAT as a reference. 

I don't see a reason to use SORT or DEEPSORT, they are far from SOTA. Afaik siamese architectures perform better than tracking-by-detection based ones for single object tracking .... or do you plan to do multi-object tracking as a pre-annotation step? I don't think the latter is possible in CVAT currently.

**Comment by malfonso0** [comment]
yes.. i was planning on doing MOT, in my videos, i not only have more than one vehicle.. but also i have annotated properties of the vehicle, like the license plate.

**Comment by dschoerk** [comment]
> i couldnt find any doc on that.

i started by getting the AI tools to work here https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

the second resource i consider helpful was this one
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/
having steps documented how to use nuclio was really helpful. creating a project, deployment, etc. previous experience with running and building docker containers is really helpful if you plan to create your own AI tool.

**Comment by malfonso0** [comment]
yes, i have already deployed my production models to cvat, in cpu and gpu, so that part is cover. i
thanks so much for your help.
